[server]
headless = false

[ui]
hideTopBar = false
hideSidebarNav = true

[theme]
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
base = "light"
